### ISSUE TITLE
DEBIAN_VERSION check is incorrect, results in uninstallable package on bullseye

### ISSUE THREAD

**Issue by rincebrain** [horsicq/build_tools#1]
https://github.com/horsicq/build_tools/blob/859f7e5acf346b785a711d58d0d20f5956277ed5/linux.sh#L43

```
$ cat /etc/debian_version
11.2
```

And then because it defaults to overriding to X_DEBIAN_VERSION=5, then

https://github.com/horsicq/XELFViewer/blob/2e2dc63f1eeba94d97a72da75c7c3cc3ecba09cd/build_dpkg.sh#L29-L33

results in a qt5-defaults dependency that isn't satisfiable on bullseye.

Perhaps
` X_DEBIAN_VERSION=$(cat /etc/debian_version | awk -F'.' '{ print $1 }')`
might do better?

**Comment by horsicq** [comment]
Thank a lot. It is really good catch. I will fix it ASAP.

**Comment by horsicq** [comment]
Fixed: https://github.com/horsicq/build_tools/commit/d6164f972d0ffcf5d0605c22c84f58a01185d09c
