### ISSUE TITLE
some wrong when i use windows bat 

### ISSUE THREAD

**Issue by sadnecc** [horsicq/build_tools#2]
![1644462809(1)](https://user-images.githubusercontent.com/8072644/153330304-ce1611ec-6c03-423d-a2f6-e01172633a97.png)

**Comment by horsicq** [comment]
Hello! Thanks a lot for the bugreport! How do you use it? Windows.but is just collwction of functions.

**Comment by sadnecc** [comment]
[wrong.txt](https://github.com/horsicq/build_tools/files/8041070/wrong.txt)

**Comment by sadnecc** [comment]
thanks!

**Comment by sadnecc** [comment]
new wrong here 
[wrong2.txt](https://github.com/horsicq/build_tools/files/8050201/wrong2.txt)

**Comment by sadnecc** [comment]
and C:\Users\Administrator\Desktop\stringsx64dbg-master\StringsPlugin\FormatWidgets\MultiSearch\multisearch.pri

add same as SearchSignatures/searchsignatureswidget.pri

**Comment by horsicq** [comment]
Thanks! I will take look.

**Comment by horsicq** [comment]
Fixed. It should work now. :)

**Comment by sadnecc** [comment]
thanks!!!

**Comment by sadnecc** [comment]
thanks！ This is the first project I compiled on git . There are still some errors reported that.But I already got strings.dll

**Comment by sadnecc** [comment]
pluginmain.cpp
StringsPlugin\pluginmain.cpp(70) : warning C4100: 'cbType' : unreferenced formal parameter
StringsPlugin\pluginmain.cpp(75) : warning C4100: 'cbType' : unreferenced formal parameter
StringsPlugin\pluginmain.cpp(109) : warning C4100: 'info' : unreferenced formal parameter
StringsPlugin\pluginmain.cpp(109) : warning C4100: 'cbType' : unreferenced formal parameter
StringsPlugin\pluginmain.cpp(125) : warning C4100: 'cbType' : unreferenced formal parameter

xbinary.cpp
StringsPlugin\Formats\xbinary.cpp(8125) : warning C4018: '<=' : signed/unsigned mismatch
StringsPlugin\Formats\xbinary.cpp(8125) : warning C4018: '<' : signed/unsigned mismatch

**Comment by sadnecc** [comment]
strings.dp64 strings.dp32  , got it ! thanks for your help

**Comment by horsicq** [comment]
It is OK. It is not errors but warnings. :)
